// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwtmfnwqucsemrnjnbkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dG1mbndxdWNzZW1ybmpuYmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTY3MzksImV4cCI6MjA1Nzg3MjczOX0.MQf-PUq8KU9hXcCQA3Y5B4JkGdS0OQY6EJdaMLL2g8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);